mel:
  x_res: 216
  y_res: 96
  n_fft: 2048
  hop_length: 512

data:
  batch_size: 1024
  num_workers: 8
  test_track_ids:
  - "3EYOJ48Et32uATr9ZmLnAo"  # The Police - Roxanne
  - "3Ti0GdlrotgwsAVBBugv0I"  # A Tribe Called Quest - Can I Kick It?
  - "5XeSAezNDk9tuw3viiCbZ3"  # James Brown - Get Up Offa That Thing
  - "4CeeEOM32jQcH3eN9Q2dGj"  # Nirvana - Smells Like Teen Spirit
  - "75FYqcxt1YEAtqDLrOeIJn"  # Bob Marley & The Wailers - Three Little Birds
  - "4NnWuGQujzWUEg0uZokO5M"  # The Cure - Just Like Heaven
  - "3spdoTYpuCpmq19tuD0bOe"  # Frank Sinatra - My Way
  - "216tRx9zfuKKILYJt3t1fi"  # The Clash - Rock the Casbah
  - "75zMKn5euxQdlkZgu4P42J"  # The Rolling Stones - Sympathy For The Devil
  - "5uvosCdMlFdTXhoazkTI5R"  # The Doors - Light My Fire
  - "15JINEqzVMv3SvJTAXAKED"  # Eminem - Love The Way You Lie
  - "69kOkLUCkxIZYexIgSG8rq"  # Daft Punk - Get Lucky (feat. Pharrell Williams and Nile Rodgers)
  - "6oVY50pmdXqLNVeK8bzomn"  # John Coltrane - My Favorite Things
  - "2mHchPRtQWet3iIS3jANr1"  # Sex Pistols - God Save The Queen
  - "0YammaEkYSeo9vQYZ1OwS6"  # David Guetta - Say My Name
  - "2eIk5ky8THuVeQg5Z5eVav"  # Andy Williams - Can't Take My Eyes Off You

trainer:
  max_epochs: 500
  accelerator: gpu
  devices: auto
