model:
  window: 2           # Length of sequences
  vector_size: 100    # Number of dimensions of embedding
  batch_words: 10000  # Number of tracks to process in each batch
  epochs: 15          # Number of iterations
  sg: 0               # Skip-gram (1) or Continuous Bag Of Words (0)

data:
  valid_examples:
  - "3EYOJ48Et32uATr9ZmLnAo"  # The Police - Roxanne
  - "3Ti0GdlrotgwsAVBBugv0I"  # A Tribe Called Quest - Can I Kick It?
  - "5XeSAezNDk9tuw3viiCbZ3"  # James Brown - Get Up Offa That Thing
  - "4CeeEOM32jQcH3eN9Q2dGj"  # Nirvana - Smells Like Teen Spirit
  - "7vggqxNKwd6xdRoYS0pQtM"  # Bob Marley & The Wailers - Three Little Birds
  - "1kqmuBbxhY420cj9IuoCkb"  # The Cure - Just Like Heaven
  - "3spdoTYpuCpmq19tuD0bOe"  # Frank Sinatra - My Way
  - "4IMvgp0WZqr9mRqpEvDKxI"  # The Clash - Rock the Casbah
  - "75zMKn5euxQdlkZgu4P42J"  # The Rolling Stones - Sympathy For The Devil
  - "5uvosCdMlFdTXhoazkTI5R"  # The Doors - Light My Fire
  - "15JINEqzVMv3SvJTAXAKED"  # Eminem - Love The Way You Lie
  - "69kOkLUCkxIZYexIgSG8rq"  # Daft Punk - Get Lucky (feat. Pharrell Williams and Nile Rodgers)
  - "6oVY50pmdXqLNVeK8bzomn"  # John Coltrane - My Favorite Things
  - "2mHchPRtQWet3iIS3jANr1"  # Sex Pistols - God Save The Queen
  - "0YammaEkYSeo9vQYZ1OwS6"  # David Guetta - Say My Name
  - "4SHZsQIdS2N1E5yqvoXF8o"  # Andy Williams - Can't Take My Eyes Off You
